import test from 'node:test'; import assert from 'node:assert/strict';
import { AIHarness,ContextCompiler,ModelGateway,ModelRouter,PromptRegistry,SkillRegistry,ToolRegistry,AIPolicyEngine,AIInputGuard,AIOutputGuard,AITrace,AIUsageRecorder,businessContextPrompt,businessContextSkill,extractBusinessContext } from '../src/ai/index.js';
import { loadAIConfig } from '../src/ai/config.js';

const output={productsServices:['peças industriais'],customerSegments:['pequenas fábricas'],mentionedSystems:['Excel'],manualControls:['controle de pedidos no Excel']};
class ExplicitTestProvider { constructor(){this.name='test-double';} async generate(request){const parsed=request.outputSchema.safeParse(output); return {provider:this.name,model:request.model,data:parsed.data,usage:{inputTokens:null,outputTokens:null,cachedTokens:null}};} }
const tenant={organizationId:'org-1',userId:'user-1',membershipId:'member-1',membershipActive:true,permissions:['discovery:read']};
function fixture(sink={records:[],async record(x){this.records.push(x);}}){ const provider=new ExplicitTestProvider(); return {sink,harness:new AIHarness({contextCompiler:new ContextCompiler({maxContextTokens:50,maxRetrievedItems:1,maxDocumentChunks:1}),policyEngine:new AIPolicyEngine({featuresEnabled:true,allowedOperations:[businessContextPrompt.id],allowedModels:['test-fast']}),promptRegistry:new PromptRegistry([businessContextPrompt]),skillRegistry:new SkillRegistry([businessContextSkill]),modelRouter:new ModelRouter({FAST:'test-fast'}),gateway:new ModelGateway(provider),inputGuard:new AIInputGuard(),outputGuard:new AIOutputGuard(),trace:new AITrace(sink)})}; }
test('operação real passa pelo harness, valida output e registra métricas desconhecidas como null',async()=>{const {harness,sink}=fixture(); const result=await extractBusinessContext(harness,tenant,'Vendemos peças industriais para pequenas fábricas e usamos Excel para controlar pedidos.'); assert.deepEqual(result.data,output); assert.equal(result.evidence.inferenceType,'FACT'); assert.equal(sink.records[0].provider,'test-double'); assert.equal(sink.records[0].inputTokens,null);});
test('isolamento tenant, budget e sanitização de segredo',()=>{const compiler=new ContextCompiler({maxContextTokens:4,maxRetrievedItems:2,maxDocumentChunks:2}); const result=compiler.compile({tenant,requirements:[],businessData:[{organizationId:'org-2',type:'CONFIRMED_FACT',sourceId:'other',content:'vazamento',trustLevel:'TRUSTED'},{organizationId:'org-1',type:'CONFIRMED_FACT',sourceId:'ok',content:'fato curto',trustLevel:'TRUSTED',relevance:1},{organizationId:'org-1',type:'USER_INPUT',sourceId:'api_key',content:'valor',trustLevel:'UNTRUSTED'}]}); assert.deepEqual(result.sourceIds,['ok']);});
test('ToolRegistry aplica permissões e UsageRecorder não inventa custo',async()=>{const tools=new ToolRegistry([{id:'read-context',description:'Leitura interna',inputSchema:{},outputSchema:{},requiredPermissions:['read'],riskLevel:'LOW',requiresApproval:false,idempotent:true}]); assert.equal(tools.listAllowed([]).length,0); assert.equal(tools.listAllowed(['read']).length,1); const records=[]; await new AIUsageRecorder({record:async x=>records.push(x)}).record({inputTokens:null}); assert.equal(records[0].cost,null);});
test('mock é bloqueado fora de teste e feature flag é explícita',()=>{assert.throws(()=>loadAIConfig({AI_PROVIDER:'mock',NODE_ENV:'production'}),/mock/); assert.equal(loadAIConfig({}).featuresEnabled,false);});
